Build_directory=~/nginx_build
User_home=~

./configure \
--prefix=$User_home/nginx-settings \
--pid-path=run/nginx.pid \
--conf-path=nginx.conf \
--http-log-path=logs/access.log \
--error-log-path=logs/error.log \
--modules-path=modules \
--http-client-body-temp-path=$User_home/nginx-settings/temp/body \
--http-fastcgi-temp-path=$User_home/nginx-settings/temp/fastcgi \
--http-proxy-temp-path=$User_home/nginx-settings/temp/proxy \
--http-scgi-temp-path=$User_home/nginx-settings/temp/scgi \
--http-uwsgi-temp-path=$User_home/nginx-settings/temp/uwsgi \
--with-compat \
--with-debug \
--with-http_ssl_module \
--with-http_stub_status_module \
--with-http_realip_module \
--with-http_auth_request_module \
--with-http_v2_module \
--with-http_dav_module \
--with-http_slice_module \
--with-threads \
--with-http_addition_module \
--with-http_flv_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_mp4_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_sub_module \
--with-mail=dynamic \
--with-mail_ssl_module \
--with-stream \
--with-stream_realip_module \
--with-stream_ssl_module \
--with-stream_ssl_preread_module \
--with-pcre=$Build_directory/pcre-8.45 \
--with-zlib=$Build_directory/zlib-1.2.12